export const COMMUNITY_CONNECT = "COMMUNITY_CONNECT";
export const COMMUNITY_CONNECT__SUCCEEDED = "COMMUNITY_CONNECT__SUCCEEDED";

export const COMMUNITY_CONNECTION__CLOSED = "COMMUNITY_CONNECTION__CLOSED";
export const COMMUNITY_CONNECTION__ERROR = "COMMUNITY_CONNECTION__ERROR";

export const COMMUNITY_CONNECTION_MESSAGE = "COMMUNITY_CONNECTION_MESSAGE";
export const COMMUNITY_CONNECTION_MESSAGE__SUCCEEDED = "COMMUNITY_CONNECTION_MESSAGE__SUCCEEDED";
export const COMMUNITY_CONNECTION_MESSAGE__FAILED = "COMMUNITY_CONNECTION_MESSAGE__FAILED";
